version: 2 
jobs:
  build:
    working_directory: ~/app
    docker:
    - image: circleci/node:lts-browsers-legacy
    steps:
    - checkout
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: build
        command: npx create-react-app redux-colorlist
    - run:
        name: test
        command: npm run jasmine
